--DML

INSERT INTO "PUBLIC". "PLANTS" ("NAME", "DESCRIPTION") VALUES ('Birch', 'Curly');
INSERT INTO "PUBLIC". "PLANTS" ("NAME", "DESCRIPTION") VALUES ('Oak', 'Strong');
INSERT INTO "PUBLIC". "PLANTS" ("NAME", "DESCRIPTION") VALUES ('Shrub', 'Bushy');
INSERT INTO "PUBLIC". "PLANTS" ("NAME", "DESCRIPTION") VALUES ('Weed', 'Green');


INSERT INTO "PUBLIC"."GARDEN_PLANTS"( "PLANT_ID", "HEALTH", "ART_PROC_DATE", "PLANTED_DATE", "REMOVED_DATE", "REMOVED", "DESCRIPTION" ) VALUES ( 1, 100, NULL, NOW(), NULL, FALSE, '');
INSERT INTO "PUBLIC"."GARDEN_PLANTS"( "PLANT_ID", "HEALTH", "ART_PROC_DATE", "PLANTED_DATE", "REMOVED_DATE", "REMOVED", "DESCRIPTION" ) VALUES ( 3, 150, NULL, NOW(), NULL, FALSE, '');
INSERT INTO "PUBLIC"."GARDEN_PLANTS"( "PLANT_ID", "HEALTH", "ART_PROC_DATE", "PLANTED_DATE", "REMOVED_DATE", "REMOVED", "DESCRIPTION" ) VALUES ( 2, 100, NULL, NOW(), NULL, FALSE, '');
INSERT INTO "PUBLIC"."GARDEN_PLANTS"( "PLANT_ID", "HEALTH", "ART_PROC_DATE", "PLANTED_DATE", "REMOVED_DATE", "REMOVED", "DESCRIPTION" ) VALUES ( 1, 110, NULL, NOW(), NULL, FALSE, '');
INSERT INTO "PUBLIC"."GARDEN_PLANTS"( "PLANT_ID", "HEALTH", "ART_PROC_DATE", "PLANTED_DATE", "REMOVED_DATE", "REMOVED", "DESCRIPTION" ) VALUES ( 1, 100, NULL, NOW(), NULL, FALSE, '');

